# Generated by Django 4.2.7 on 2023-11-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('post_number', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='gaurav raghav', max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
