# Generated by Django 4.2.7 on 2023-11-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_name_blogpost_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='user_name',
            field=models.CharField(default='Gaurav Raghav', max_length=255),
        ),
    ]
