# Generated by Django 4.1.2 on 2023-12-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_blogpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='assets/imgs/gaurav.jpeg', upload_to='post_images/'),
        ),
    ]
